version: '3'

services:
  app:
    container_name: app
    build: .
    tty: true
    environment:
      - WATCHPACK_POLLING=true
    working_dir: /app
    ports:
      - 80:3000
    volumes:
      - .:/app:cached
      - node_modules:/app/node_modules

volumes:
  node_modules: {}
