version: "3.9"
services:
  db:
    image: postgres
    volumes:
      - postgres_volume:/var/lib/postgresql/data
    environment:
      # POSTGRES_DB: postgres
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
    restart: always
    networks:
      - external
  redis:
    image: redis
    ports:
      - "6379:6379"
    volumes:
      - redis:/data
  api:
    build: .
    command: sh
    volumes:
      - .:/api
    ports:
      - "3000:3000"
    depends_on:
      - db
      - redis
    environment:
      REDIS_URL: redis://redis:6379
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
    tty: true
    networks:
      - external

volumes:
  redis:
  postgres_volume:

networks:
  external:
    external: true
